---
- hosts: master
  tasks:
    - name: get join command from master
      shell: kubeadm token create --print-join-command
      register: join_cmd
      become: no

- hosts: minions
  tasks:
    - name: join cluster
      shell: "{{ hostvars[groups['master'][0]]['join_cmd'].stdout_lines[-1] }}"
      become: yes
